---

- name: "Ensure that the necessary python modules are installed"
  ansible.builtin.dnf:
    name: "python3-pip"
    state: "present"

- name: "Ensure ansible-lint is available"
  ansible.builtin.command: "pip3 install ansible-lint"
  register: lint_install_result
  changed_when: lint_install_result.rc == 0
