---

- name: "Ensure the remote directory exists"
  ansible.builtin.file:
    path: "{{ remote_path }}"
    state: "directory"
    mode: "0700"
    owner: "{{ rhis_user }}"
    group: "{{ rhis_user }}"

- name: "Copy the files to remote host"
  ansible.builtin.copy:
    src: "{{ vault_file }}"
    dest: "{{ remote_path }}/"
    mode: "0600"
    owner: "{{ rhis_user }}"
    group: "{{ rhis_user }}"
  loop: "{{ vault_files_list }}"
  loop_control:
    loop_var: vault_file
