---

# Add your git user and email

- name: "Add git user and email to git global configruation"
  when: git_configs is defined and (git_configs | length) > 0
  community.general.git_config:
    name: "{{ git_config.name }}"
    scope: "{{ git_config.scope }}"
    value: "{{ git_config.value }}"
  loop: "{{ git_configs }}"
  loop_control:
    loop_var: git_config
  become: false
